package jdbc;
// Generated Mar 28, 2017 5:17:44 PM by Hibernate Tools 4.3.1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String suppliername;
     private String brandname;
     private String catname;
     private String description;

    public Category() {
    }

    public Category(Integer id, String suppliername, String brandname, String catname, String description) {
        this.id = id;
        this.suppliername = suppliername;
        this.brandname = brandname;
        this.catname = catname;
        this.description = description;
    }

    public Category(Integer id) {
        this.id = id;
    }

    public Category(String suppliername, String brandname, String catname, String description) {
       this.suppliername = suppliername;
       this.brandname = brandname;
       this.catname = catname;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSuppliername() {
        return this.suppliername;
    }
    
    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername;
    }
    public String getBrandname() {
        return this.brandname;
    }
    
    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }
    public String getCatname() {
        return this.catname;
    }
    
    public void setCatname(String catname) {
        this.catname = catname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


