package jdbc;
// Generated Mar 28, 2017 5:17:44 PM by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String custname;
     private String contactno;
     private String address;

    public Customer() {
    }

    public Customer(Integer id, String custname, String contactno, String address) {
        this.id = id;
        this.custname = custname;
        this.contactno = contactno;
        this.address = address;
    }

    public Customer(Integer id) {
        this.id = id;
    }

    public Customer(String custname, String contactno, String address) {
       this.custname = custname;
       this.contactno = contactno;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCustname() {
        return this.custname;
    }
    
    public void setCustname(String custname) {
        this.custname = custname;
    }
    public String getContactno() {
        return this.contactno;
    }
    
    public void setContactno(String contactno) {
        this.contactno = contactno;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


