package jdbc;
// Generated Mar 28, 2017 5:17:44 PM by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private String uname;
     private String fullname;
     private String mobile;
     private String email;
     private String address;
     private String position;
     private Double salary;
     private String joindate;
     private byte[] image;

    public Employee() {
    }

    public Employee(Integer id) {
        this.id = id;
    }

    public Employee(Integer id, String uname, String fullname, String mobile, String email, String address, String position, Double salary, String joindate, byte[] image) {
        this.id = id;
        this.uname = uname;
        this.fullname = fullname;
        this.mobile = mobile;
        this.email = email;
        this.address = address;
        this.position = position;
        this.salary = salary;
        this.joindate = joindate;
        this.image = image;
    }

    public Employee(Integer id, String uname, String fullname, String mobile, String email, String address, String position, Double salary, String joindate) {
        this.id = id;
        this.uname = uname;
        this.fullname = fullname;
        this.mobile = mobile;
        this.email = email;
        this.address = address;
        this.position = position;
        this.salary = salary;
        this.joindate = joindate;
    }

    public Employee(String uname, String fullname, String mobile, String email, String address, String position, Double salary, String joindate) {
        this.uname = uname;
        this.fullname = fullname;
        this.mobile = mobile;
        this.email = email;
        this.address = address;
        this.position = position;
        this.salary = salary;
        this.joindate = joindate;
    }

    public Employee(String uname, String fullname, String mobile, String email, String address, String position, Double salary, String joindate, byte[] image) {
       this.uname = uname;
       this.fullname = fullname;
       this.mobile = mobile;
       this.email = email;
       this.address = address;
       this.position = position;
       this.salary = salary;
       this.joindate = joindate;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public Double getSalary() {
        return this.salary;
    }
    
    public void setSalary(Double salary) {
        this.salary = salary;
    }
    public String getJoindate() {
        return this.joindate;
    }
    
    public void setJoindate(String joindate) {
        this.joindate = joindate;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


