package jdbc;
// Generated Apr 10, 2017 6:56:27 PM by Hibernate Tools 4.3.1

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer pid;
     private String pname;
     private Integer qty;
     private Double pprice;
     private Double sprice;
     private String pdescription;
     private String suppliername;
     private String brandname;
     private String catname;
     private String unit;
     private String warranty;
     private String pdate;
     private byte[] pimage;

    public Product() {
    }

    public Product(Integer pid) {
        this.pid = pid;
    }

    public Product(Integer pid, String pname, Integer qty, Double pprice, Double sprice, String pdescription, String suppliername, String brandname, String catname, String unit, String warranty, String pdate, byte[] pimage) {
        this.pid = pid;
        this.pname = pname;
        this.qty = qty;
        this.pprice = pprice;
        this.sprice = sprice;
        this.pdescription = pdescription;
        this.suppliername = suppliername;
        this.brandname = brandname;
        this.catname = catname;
        this.unit = unit;
        this.warranty = warranty;
        this.pdate = pdate;
        this.pimage = pimage;
    }

    public Product(String pname, Integer qty, Double pprice, Double sprice, String pdescription, String suppliername, String brandname, String catname, String unit, String warranty, String pdate, byte[] pimage) {
       this.pname = pname;
       this.qty = qty;
       this.pprice = pprice;
       this.sprice = sprice;
       this.pdescription = pdescription;
       this.suppliername = suppliername;
       this.brandname = brandname;
       this.catname = catname;
       this.unit = unit;
       this.warranty = warranty;
       this.pdate = pdate;
       this.pimage = pimage;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPprice() {
        return this.pprice;
    }
    
    public void setPprice(Double pprice) {
        this.pprice = pprice;
    }
    public Double getSprice() {
        return this.sprice;
    }
    
    public void setSprice(Double sprice) {
        this.sprice = sprice;
    }
    public String getPdescription() {
        return this.pdescription;
    }
    
    public void setPdescription(String pdescription) {
        this.pdescription = pdescription;
    }
    public String getSuppliername() {
        return this.suppliername;
    }
    
    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername;
    }
    public String getBrandname() {
        return this.brandname;
    }
    
    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }
    public String getCatname() {
        return this.catname;
    }
    
    public void setCatname(String catname) {
        this.catname = catname;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }
    public String getPdate() {
        return this.pdate;
    }
    
    public void setPdate(String pdate) {
        this.pdate = pdate;
    }
    public byte[] getPimage() {
        return this.pimage;
    }
    
    public void setPimage(byte[] pimage) {
        this.pimage = pimage;
    }

}


