package jdbc;
// Generated Apr 10, 2017 7:01:22 PM by Hibernate Tools 4.3.1



/**
 * Sale generated by hbm2java
 */
public class Sale  implements java.io.Serializable {


     private Integer id;
     private Integer pid;
     private String custname;
     private Double sprice;
     private Integer qty;
     private String sdate;
     private String warranty;
     private Double totalprice;
     private String productname;

    public Sale() {
    }

    public Sale(Integer id) {
        this.id = id;
    }

    public Sale(Integer id, Integer pid, String custname, Double sprice, Integer qty, String sdate, String warranty, Double totalprice, String productname) {
        this.id = id;
        this.pid = pid;
        this.custname = custname;
        this.sprice = sprice;
        this.qty = qty;
        this.sdate = sdate;
        this.warranty = warranty;
        this.totalprice = totalprice;
        this.productname = productname;
    }

    public Sale(Integer pid, String custname, Double sprice, Integer qty, String sdate, String warranty, Double totalprice, String productname) {
       this.pid = pid;
       this.custname = custname;
       this.sprice = sprice;
       this.qty = qty;
       this.sdate = sdate;
       this.warranty = warranty;
       this.totalprice = totalprice;
       this.productname = productname;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getCustname() {
        return this.custname;
    }
    
    public void setCustname(String custname) {
        this.custname = custname;
    }
    public Double getSprice() {
        return this.sprice;
    }
    
    public void setSprice(Double sprice) {
        this.sprice = sprice;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public String getSdate() {
        return this.sdate;
    }
    
    public void setSdate(String sdate) {
        this.sdate = sdate;
    }
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }
    public Double getTotalprice() {
        return this.totalprice;
    }
    
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }




}


