package jdbc;
// Generated Mar 28, 2017 5:17:44 PM by Hibernate Tools 4.3.1



/**
 * Unit generated by hbm2java
 */
public class Unit  implements java.io.Serializable {


     private Integer id;
     private String unitname;
     private Integer unitsize;

    public Unit() {
    }

    public Unit(Integer id, String unitname, Integer unitsize) {
        this.id = id;
        this.unitname = unitname;
        this.unitsize = unitsize;
    }

    public Unit(Integer id) {
        this.id = id;
    }

    public Unit(String unitname, Integer unitsize) {
       this.unitname = unitname;
       this.unitsize = unitsize;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUnitname() {
        return this.unitname;
    }
    
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }
    public Integer getUnitsize() {
        return this.unitsize;
    }
    
    public void setUnitsize(Integer unitsize) {
        this.unitsize = unitsize;
    }




}


