package jdbc;
// Generated Mar 28, 2017 5:17:44 PM by Hibernate Tools 4.3.1



/**
 * Warranty generated by hbm2java
 */
public class Warranty  implements java.io.Serializable {


     private Integer id;
     private String warrantytype;
     private String warrantydays;
     private String description;

    public Warranty() {
    }

    public Warranty(Integer id, String warrantytype, String warrantydays, String description) {
        this.id = id;
        this.warrantytype = warrantytype;
        this.warrantydays = warrantydays;
        this.description = description;
    }

    public Warranty(Integer id) {
        this.id = id;
    }

    public Warranty(String warrantytype, String warrantydays, String description) {
       this.warrantytype = warrantytype;
       this.warrantydays = warrantydays;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getWarrantytype() {
        return this.warrantytype;
    }
    
    public void setWarrantytype(String warrantytype) {
        this.warrantytype = warrantytype;
    }
    public String getWarrantydays() {
        return this.warrantydays;
    }
    
    public void setWarrantydays(String warrantydays) {
        this.warrantydays = warrantydays;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


